version: '1.0'

my:
  id: 1007
  ip: 10.176.34.171
  name: 'zkx'
  description: 'DVE Center zkx'
  garnet_path: "/home/zkx/Garnet"
  base_path: "/home/zkx/DAVE/DVE"

server:
  port: 9090

ssl:
  client-auth: true
  key-store-password: 'agopkljsfoi'
  key-store-type: JKS
  keystore-path: jwt.jks
  trust-store-password: 'dfjlkghalgd'
  truststore-path: truststore.jks

spring:
  application:
    name: DveCenter
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.176.34.171:3306/zkx_center
      username: zkx
      password: makeMPLgreat*2
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID

threadpool:
  # 核心线程池大小
  corePoolSize: 5   
  # 最大线程数
  maxPoolSize: 10
  # 队列容量
  queueCapacity: 100
  # 活跃时间：非核心线程空闲时间超过这个时间就会被回收
  keepAliveSeconds: 60
  # 主线程等待子线程执行时间
  awaitTerminationSeconds: 6000
  # 线程名字前缀
  threadNamePrefix: 'DVE-Center-'

file:
  upload-base-dir: "/home/zkx/DAVE/Files/"
  download-base-dir: "/home/zkx/DAVE/ApplicationFiles/"