version: '1.0'

my:
  id: 2
  ip: 10.176.34.173
  name: '173'

server:
  port: 8080

ssl:
  client-auth: true
  key-store-password: '1834567189023'
  key-store-type: JKS
  keystore-path: jwt.jks
  trust-store-password: '53407390786'
  truststore-path: truststore.jks

spring:
  application:
    name: DveAgent
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.176.34.171:3306/test
      username: nhy
      password: makeMPLgreat*2

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
