<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.dsg</groupId>
        <artifactId>davex</artifactId>
        <version>0.0.1</version>
    </parent>

    <groupId>org.dsg</groupId>
    <artifactId>davex-center</artifactId>
    <version>0.0.1</version>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>org.dsg</groupId>
            <artifactId>davex-base</artifactId>
            <version>0.0.1</version>
        </dependency>
        <!-- Center 发送 MPC 任务时直接使用 Center-Agent 通信协议。 -->
        <dependency>
            <groupId>org.dsg</groupId>
            <artifactId>davex-contract</artifactId>
            <version>0.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-csv</artifactId>
            <version>1.10.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>2.0.29</version>
        </dependency>
        <dependency>
            <groupId>com.hankcs</groupId>
            <artifactId>hanlp</artifactId>
            <version>portable-1.7.6</version>
        </dependency>
        <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>java-jwt</artifactId>
            <version>3.18.2</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <fork>true</fork>
                    <addResources>true</addResources>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>