version: '1.0'

my:
  id: 9
  ip: 10.176.34.173
  name: '173'
  description: 'DVE Agent 173'
  garnet_path: "/home/nhy/garnet"
server:
  port: 8081

ssl:
  client-auth: false
  key-store-password: 'agopkljsfoi'
  key-store-type: JKS
  keystore-path: jwt.jks
  trust-store-password: 'dfjlkghalgd'
  truststore-path: truststore.jks

spring:
  application:
    name: DveAgent
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.176.34.173:3306/agent
      username: zw
      password: newpass

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
