version: '1.0'

my:
  id: 5
  ip: 172.20.10.6
  name: 'drt'
  description: 'Dve Agent 171'
  garnet_path: "/home/"

server:
  port: 8080

ssl:
  client-auth: false
  key-store-password: 'agopkljsfoi'
  key-store-type: JKS
  keystore-path: jwt.jks
  trust-store-password: 'dfjlkghalgd'
  truststore-path: truststore.jks

spring:
  application:
    name: DveAgent
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.176.37.50:3306/agent
      username: drt
      password: Drt1951725
#      url: jdbc:mysql://172.20.10.5:3306/center
#      username: zkx
#      password: 123456

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
