version: '1.0'

my:
  id: 5
  ip: 10.176.37.50
  name: 'drt'
  description: 'DVE Agent 171'
  garnet_path: "/disk2/Garnet/Garnet"
  base_path: "/disk2"
  dve_type: "DVE_AGENT"

server:
  port: 8080

ssl:
  client-auth: false
  key-store-password: 'agopkljsfoi'
  key-store-type: JKS
  keystore-path: jwt.jks
  trust-store-password: 'dfjlkghalgd'
  truststore-path: truststore.jks

spring:
  application:
    name: DveAgent
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/test
#      username: root
#      password: Drt1951725

      url: jdbc:mysql://10.176.37.50:3306/agent
      username: drt
      password: Drt1951725

#      url: jdbc:mysql://172.20.10.5:3306/center
#      username: zkx
#      password: 123456

#      url: jdbc:mysql://10.176.34.171:3306/agent
#      username: nhy
#      password: makeMPLgreat*2

  jackson:
    serialization:
      write-dates-as-timestamps: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID

threadpool:
  # 核心线程池大小
  corePoolSize: 5
  # 最大线程数
  maxPoolSize: 10
  # 队列容量
  queueCapacity: 100
  # 活跃时间：非核心线程空闲时间超过这个时间就会被回收
  keepAliveSeconds: 60
  # 主线程等待子线程执行时间
  awaitTerminationSeconds: 6000
  # 线程名字前缀
  threadNamePrefix: 'DVE-Agent-'

#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    DveAgent.module.directory: DEBUG
#  file:
#    name: logs/application.log
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
